# Generated by Django 3.2.8 on 2023-08-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_driver_addressid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='RoleID',
        ),
        migrations.AlterField(
            model_name='driver',
            name='AddressID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.address'),
        ),
    ]
